version: '3.1'

services:
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 5050:8080