version: '3.1'
services:
  db:
    image: postgres:latest
    container_name: splitpaldb
    env_file:
      - .env
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 5050:8080